/*
 * This file is generated by jOOQ.
 */
package com.demo.codegen;


import com.demo.codegen.tables.Account;
import com.demo.codegen.tables.FtpServer;
import com.demo.codegen.tables.FtpServerAccount;
import com.demo.codegen.tables.Station;
import com.demo.codegen.tables.Task;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.account</code>.
     */
    public static final Account ACCOUNT = Account.ACCOUNT;

    /**
     * The table <code>public.ftp_server</code>.
     */
    public static final FtpServer FTP_SERVER = FtpServer.FTP_SERVER;

    /**
     * The table <code>public.ftp_server_account</code>.
     */
    public static final FtpServerAccount FTP_SERVER_ACCOUNT = FtpServerAccount.FTP_SERVER_ACCOUNT;

    /**
     * The table <code>public.station</code>.
     */
    public static final Station STATION = Station.STATION;

    /**
     * The table <code>public.task</code>.
     */
    public static final Task TASK = Task.TASK;
}
