
version: '3.1'


services:

  main-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
    volumes:
      - main-db-data:/var/lib/postgresql/data
      - ./ddl.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: "gitlab_runner"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/etc/gitlab-runner
      - /cache:/cache
    restart: always
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: masoud
      MINIO_ROOT_PASSWORD: Strong#Pass#2022
    command: server --console-address ":9001" /data
  db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - sonarqube_db:/var/lib/postgresql/data

  sonarqube:
    image: sonarqube:7.9.1-community
    environment:
      SONARQUBE_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonar
    ports:
      - 9002:9000
    depends_on:
      - db
  runner2:
    image: gitlab/gitlab-runner:latest
    environment:
      CI_SERVER_URL: https://gitlab.com/
      REGISTRATION_TOKEN: GR1348941LSjLhGurEyANmbB8vRDq
      RUNNER_EXECUTOR: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  main-db-data:
  minio_storage: {}
  sonarqube_db: