/*
 * This file is generated by jOOQ.
 */
package com.demo.codegen.tables.records;


import com.demo.codegen.tables.FtpServerAccount;

import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FtpServerAccountRecord extends TableRecordImpl<FtpServerAccountRecord> implements Record7<String, String, String, String, String, String, Timestamp> {

    private static final long serialVersionUID = -781432310;

    /**
     * Setter for <code>public.ftp_server_account.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.ftp_server_account.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.ftp_server_account.account_id</code>.
     */
    public void setAccountId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.ftp_server_account.account_id</code>.
     */
    public String getAccountId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.ftp_server_account.ftp_server_id</code>.
     */
    public void setFtpServerId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.ftp_server_account.ftp_server_id</code>.
     */
    public String getFtpServerId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.ftp_server_account.account</code>.
     */
    public void setAccount(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.ftp_server_account.account</code>.
     */
    public String getAccount() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.ftp_server_account.password</code>.
     */
    public void setPassword(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.ftp_server_account.password</code>.
     */
    public String getPassword() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.ftp_server_account.status</code>.
     */
    public void setStatus(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.ftp_server_account.status</code>.
     */
    public String getStatus() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.ftp_server_account.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.ftp_server_account.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<String, String, String, String, String, String, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<String, String, String, String, String, String, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return FtpServerAccount.FTP_SERVER_ACCOUNT.ID;
    }

    @Override
    public Field<String> field2() {
        return FtpServerAccount.FTP_SERVER_ACCOUNT.ACCOUNT_ID;
    }

    @Override
    public Field<String> field3() {
        return FtpServerAccount.FTP_SERVER_ACCOUNT.FTP_SERVER_ID;
    }

    @Override
    public Field<String> field4() {
        return FtpServerAccount.FTP_SERVER_ACCOUNT.ACCOUNT;
    }

    @Override
    public Field<String> field5() {
        return FtpServerAccount.FTP_SERVER_ACCOUNT.PASSWORD;
    }

    @Override
    public Field<String> field6() {
        return FtpServerAccount.FTP_SERVER_ACCOUNT.STATUS;
    }

    @Override
    public Field<Timestamp> field7() {
        return FtpServerAccount.FTP_SERVER_ACCOUNT.CREATE_TIME;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getAccountId();
    }

    @Override
    public String component3() {
        return getFtpServerId();
    }

    @Override
    public String component4() {
        return getAccount();
    }

    @Override
    public String component5() {
        return getPassword();
    }

    @Override
    public String component6() {
        return getStatus();
    }

    @Override
    public Timestamp component7() {
        return getCreateTime();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getAccountId();
    }

    @Override
    public String value3() {
        return getFtpServerId();
    }

    @Override
    public String value4() {
        return getAccount();
    }

    @Override
    public String value5() {
        return getPassword();
    }

    @Override
    public String value6() {
        return getStatus();
    }

    @Override
    public Timestamp value7() {
        return getCreateTime();
    }

    @Override
    public FtpServerAccountRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public FtpServerAccountRecord value2(String value) {
        setAccountId(value);
        return this;
    }

    @Override
    public FtpServerAccountRecord value3(String value) {
        setFtpServerId(value);
        return this;
    }

    @Override
    public FtpServerAccountRecord value4(String value) {
        setAccount(value);
        return this;
    }

    @Override
    public FtpServerAccountRecord value5(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public FtpServerAccountRecord value6(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public FtpServerAccountRecord value7(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public FtpServerAccountRecord values(String value1, String value2, String value3, String value4, String value5, String value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FtpServerAccountRecord
     */
    public FtpServerAccountRecord() {
        super(FtpServerAccount.FTP_SERVER_ACCOUNT);
    }

    /**
     * Create a detached, initialised FtpServerAccountRecord
     */
    public FtpServerAccountRecord(String id, String accountId, String ftpServerId, String account, String password, String status, Timestamp createTime) {
        super(FtpServerAccount.FTP_SERVER_ACCOUNT);

        set(0, id);
        set(1, accountId);
        set(2, ftpServerId);
        set(3, account);
        set(4, password);
        set(5, status);
        set(6, createTime);
    }
}
