/*
 * This file is generated by jOOQ.
 */
package com.demo.codegen.tables.records;


import com.demo.codegen.tables.Station;

import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StationRecord extends TableRecordImpl<StationRecord> implements Record7<String, String, String, String, String, String, Timestamp> {

    private static final long serialVersionUID = 430320445;

    /**
     * Setter for <code>public.station.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.station.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.station.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.station.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.station.task_queue</code>.
     */
    public void setTaskQueue(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.station.task_queue</code>.
     */
    public String getTaskQueue() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.station.notify_queue</code>.
     */
    public void setNotifyQueue(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.station.notify_queue</code>.
     */
    public String getNotifyQueue() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.station.status</code>.
     */
    public void setStatus(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.station.status</code>.
     */
    public String getStatus() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.station.ftp_server_id</code>.
     */
    public void setFtpServerId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.station.ftp_server_id</code>.
     */
    public String getFtpServerId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.station.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.station.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<String, String, String, String, String, String, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<String, String, String, String, String, String, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Station.STATION.ID;
    }

    @Override
    public Field<String> field2() {
        return Station.STATION.NAME;
    }

    @Override
    public Field<String> field3() {
        return Station.STATION.TASK_QUEUE;
    }

    @Override
    public Field<String> field4() {
        return Station.STATION.NOTIFY_QUEUE;
    }

    @Override
    public Field<String> field5() {
        return Station.STATION.STATUS;
    }

    @Override
    public Field<String> field6() {
        return Station.STATION.FTP_SERVER_ID;
    }

    @Override
    public Field<Timestamp> field7() {
        return Station.STATION.CREATE_TIME;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getTaskQueue();
    }

    @Override
    public String component4() {
        return getNotifyQueue();
    }

    @Override
    public String component5() {
        return getStatus();
    }

    @Override
    public String component6() {
        return getFtpServerId();
    }

    @Override
    public Timestamp component7() {
        return getCreateTime();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getTaskQueue();
    }

    @Override
    public String value4() {
        return getNotifyQueue();
    }

    @Override
    public String value5() {
        return getStatus();
    }

    @Override
    public String value6() {
        return getFtpServerId();
    }

    @Override
    public Timestamp value7() {
        return getCreateTime();
    }

    @Override
    public StationRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public StationRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public StationRecord value3(String value) {
        setTaskQueue(value);
        return this;
    }

    @Override
    public StationRecord value4(String value) {
        setNotifyQueue(value);
        return this;
    }

    @Override
    public StationRecord value5(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public StationRecord value6(String value) {
        setFtpServerId(value);
        return this;
    }

    @Override
    public StationRecord value7(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public StationRecord values(String value1, String value2, String value3, String value4, String value5, String value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StationRecord
     */
    public StationRecord() {
        super(Station.STATION);
    }

    /**
     * Create a detached, initialised StationRecord
     */
    public StationRecord(String id, String name, String taskQueue, String notifyQueue, String status, String ftpServerId, Timestamp createTime) {
        super(Station.STATION);

        set(0, id);
        set(1, name);
        set(2, taskQueue);
        set(3, notifyQueue);
        set(4, status);
        set(5, ftpServerId);
        set(6, createTime);
    }
}
