/*
 * This file is generated by jOOQ.
 */
package com.demo.codegen.tables.records;


import com.demo.codegen.tables.Task;

import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TaskRecord extends UpdatableRecordImpl<TaskRecord> implements Record9<String, String, String, String, String, Timestamp, String, Timestamp, String> {

    private static final long serialVersionUID = 1706241159;

    /**
     * Setter for <code>public.task.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.task.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.task.origin_ftp_server_id</code>.
     */
    public void setOriginFtpServerId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.task.origin_ftp_server_id</code>.
     */
    public String getOriginFtpServerId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.task.dest_ftp_server_id</code>.
     */
    public void setDestFtpServerId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.task.dest_ftp_server_id</code>.
     */
    public String getDestFtpServerId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.task.file_path</code>.
     */
    public void setFilePath(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.task.file_path</code>.
     */
    public String getFilePath() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.task.status</code>.
     */
    public void setStatus(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.task.status</code>.
     */
    public String getStatus() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.task.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.task.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>public.task.create_account_id</code>.
     */
    public void setCreateAccountId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.task.create_account_id</code>.
     */
    public String getCreateAccountId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.task.finish_time</code>.
     */
    public void setFinishTime(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.task.finish_time</code>.
     */
    public Timestamp getFinishTime() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>public.task.dest_account_id</code>.
     */
    public void setDestAccountId(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.task.dest_account_id</code>.
     */
    public String getDestAccountId() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<String, String, String, String, String, Timestamp, String, Timestamp, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<String, String, String, String, String, Timestamp, String, Timestamp, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Task.TASK.ID;
    }

    @Override
    public Field<String> field2() {
        return Task.TASK.ORIGIN_FTP_SERVER_ID;
    }

    @Override
    public Field<String> field3() {
        return Task.TASK.DEST_FTP_SERVER_ID;
    }

    @Override
    public Field<String> field4() {
        return Task.TASK.FILE_PATH;
    }

    @Override
    public Field<String> field5() {
        return Task.TASK.STATUS;
    }

    @Override
    public Field<Timestamp> field6() {
        return Task.TASK.CREATE_TIME;
    }

    @Override
    public Field<String> field7() {
        return Task.TASK.CREATE_ACCOUNT_ID;
    }

    @Override
    public Field<Timestamp> field8() {
        return Task.TASK.FINISH_TIME;
    }

    @Override
    public Field<String> field9() {
        return Task.TASK.DEST_ACCOUNT_ID;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getOriginFtpServerId();
    }

    @Override
    public String component3() {
        return getDestFtpServerId();
    }

    @Override
    public String component4() {
        return getFilePath();
    }

    @Override
    public String component5() {
        return getStatus();
    }

    @Override
    public Timestamp component6() {
        return getCreateTime();
    }

    @Override
    public String component7() {
        return getCreateAccountId();
    }

    @Override
    public Timestamp component8() {
        return getFinishTime();
    }

    @Override
    public String component9() {
        return getDestAccountId();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getOriginFtpServerId();
    }

    @Override
    public String value3() {
        return getDestFtpServerId();
    }

    @Override
    public String value4() {
        return getFilePath();
    }

    @Override
    public String value5() {
        return getStatus();
    }

    @Override
    public Timestamp value6() {
        return getCreateTime();
    }

    @Override
    public String value7() {
        return getCreateAccountId();
    }

    @Override
    public Timestamp value8() {
        return getFinishTime();
    }

    @Override
    public String value9() {
        return getDestAccountId();
    }

    @Override
    public TaskRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public TaskRecord value2(String value) {
        setOriginFtpServerId(value);
        return this;
    }

    @Override
    public TaskRecord value3(String value) {
        setDestFtpServerId(value);
        return this;
    }

    @Override
    public TaskRecord value4(String value) {
        setFilePath(value);
        return this;
    }

    @Override
    public TaskRecord value5(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public TaskRecord value6(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public TaskRecord value7(String value) {
        setCreateAccountId(value);
        return this;
    }

    @Override
    public TaskRecord value8(Timestamp value) {
        setFinishTime(value);
        return this;
    }

    @Override
    public TaskRecord value9(String value) {
        setDestAccountId(value);
        return this;
    }

    @Override
    public TaskRecord values(String value1, String value2, String value3, String value4, String value5, Timestamp value6, String value7, Timestamp value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TaskRecord
     */
    public TaskRecord() {
        super(Task.TASK);
    }

    /**
     * Create a detached, initialised TaskRecord
     */
    public TaskRecord(String id, String originFtpServerId, String destFtpServerId, String filePath, String status, Timestamp createTime, String createAccountId, Timestamp finishTime, String destAccountId) {
        super(Task.TASK);

        set(0, id);
        set(1, originFtpServerId);
        set(2, destFtpServerId);
        set(3, filePath);
        set(4, status);
        set(5, createTime);
        set(6, createAccountId);
        set(7, finishTime);
        set(8, destAccountId);
    }
}
