system.url-prefix: "https://jyasuu-glorious-space-garbanzo-x59jv75wv6jhprr-9000.preview.app.github.dev/"
mail.backend: 'smtp'
mail.host: 'smtp.gmail.com'
mail.port: 587
mail.username: 'you@gmail.com'
mail.password: 'yourpassword'
mail.use-tls: true
