version: '3'
services:
  demo:
    image: jyasu/demo-image:latest
    restart: always
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --label-enable --interval 30 jyasu/demo-image:latest
    restart: always