version: '3'
services:
  vault:
    image: vault
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_ADDR: http://127.0.0.1:8200
    command: vault server -dev -dev-root-token-id=root
