version: '3'
services:
  mongo:
    image: mongo:4.2
    volumes:
      - mongo_data:/data/db
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  graylog:
    image: graylog/graylog:4.2.0
    environment:
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_SERVER_TIMEZONE=UTC
    depends_on:
      - mongo
      - elasticsearch
    ports:
      - 9000:9000
      - 12201:12201/udp
      - 1514:1514/udp
    volumes:
      - graylog_data:/usr/share/graylog/data
volumes:
  mongo_data:
  es_data:
  graylog_data:
